//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Win32Project.rc
//
#define IDC_MYICON                      2
#define IDD_WIN32PROJECT_DIALOG         102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_WIN32PROJECT                107
#define IDI_SMALL                       108
#define IDC_WIN32PROJECT                109
#define IDR_MAINFRAME                   128
#define IDD_DIALO_RegistroN             130
#define IDD_DIALO_RegistroNuevoAdmin    130
#define IDD_DIALOG1                     131
#define IDD_DIALO_Menu                  131
#define IDD_DIALO_MenuPrincipal         131
#define IDD_DIALO_OpcionesUsuario       132
#define IDD_DIALO_MostrarUsuario        133
#define IDD_DIALO_RegistrarUsuario      134
#define IDD_DIALO_ActualizacionUsuario  135
#define IDD_DIALO_BorrarUsuario         136
#define IDD_DIALO_OpcionesCliente       137
#define IDD_DIALO_OpcionesCajero        138
#define IDD_DIALO_OpcionesPromocion     139
#define IDD_DIALO_OpcionesConsumo       140
#define IDD_DIALO_RegistrarCliente      141
#define IDD_DIALO_RegistrarCajero       142
#define IDD_DIALO_RegistrarPromocion    143
#define IDD_DIALO_RegistrarConsumo      144
#define IDD_DIALO_BorrarCliente         145
#define IDD_DIALO_BorrarCajero          146
#define IDD_DIALO_BorrarPromocion       147
#define IDD_DIALO_BorrarConsumo         148
#define IDD_DIALO_MostrarCliente        149
#define IDD_DIALO_MostrarCajero         150
#define IDD_DIALO_MostrarPromocion      151
#define IDD_DIALO_MostrarConsumo        152
#define IDD_DIALO_ActualizacionCliente  153
#define IDD_DIALO_ActualizacionCajero   154
#define IDD_DIALO_ActualizacionPromocion 155
#define IDD_DIALOG3                     156
#define IDD_DIALO_ActualizacionConsumo  156
#define IDD_DIALO_INICIO                1001
#define IDD_DIALO_InicioDeSeccion       1001
#define IDD_DIALO                       1002
#define IDC_EDIT2                       1005
#define IDC_EDIT3                       1006
#define IDC_EDIT9                       1007
#define IDC_EDIT1                       1008
#define IDC_EDIT_NOMBRE                 1008
#define IDC_EDIT4                       1009
#define IDC_EDIT_NOMBRE2                1009
#define IDC_EDIT_USERNAME               1009
#define IDC_BUTTON1                     1010
#define IDC_EDIT_TELEFONO               1010
#define IDC_EDIT5                       1011
#define IDC_BUTTON2                     1011
#define IDC_EDIT_EMAIL                  1011
#define IDC_BUTTON3                     1012
#define IDC_EDIT6                       1012
#define IDC_LIST1                       1012
#define IDC_BUTTON4                     1013
#define IDC_EDIT7                       1013
#define IDC_LIST2                       1013
#define IDC_BUTTON5                     1014
#define IDC_EDIT8                       1014
#define IDC_LIST3                       1015
#define ID_BTN_INICIO_SECCION           1016
#define ID_BTN_REGISTRARCE              1017
#define IDC_COMBO_COMERCIOS             1018
#define IDC_BTN_GUARDAR                 1020
#define IDC_EDIT_PASSWORD               1021
#define IDC_EDIT_ALIAS                  1022
#define IDC_BTN_OPT_USUARIOS            1023
#define IDC_BTN_OPT_CLIENTES            1024
#define IDC_BTN_OPT_PROMOCIONES         1025
#define IDC_BTN_OPT_CONSUMOS            1026
#define IDC_LIST_USUARIOS               1027
#define IDC_BTN_NUEVO_USUARIO           1028
#define IDC_BTN_ACTUALIZAR_USUARIO      1029
#define IDC_BTN_BORRAR_USUARIO          1030
#define IDC_STATIC_NOMBRE_COMERSIO      1031
#define IDC_RADIO_ADMIN                 1032
#define IDC_STATIC_FECHA                1032
#define IDC_RADIO_CAJERO                1033
#define IDC_LIST_CLIENTES               1033
#define IDC_BTN_NUEVO_CLIENTE           1034
#define IDC_BTN_ACTUALIZAR_CLIENTE      1035
#define IDC_BTN_BORRAR_CLIENTE          1036
#define IDC_BTN_NUEVO_CONSUMO           1036
#define IDC_LIST_PROMOCIONES            1037
#define IDC_BTN_NUEVO_PROMOCIONES       1038
#define IDC_BTN_ACTUALIZAR_PROMOCION    1039
#define IDC_BTN_BORRAR_PROMOCION        1040
#define IDC_BUTTON_NOMBRE_PROMOCION     1041
#define IDC_EDIT_MONTO                  1042
#define IDC_EDIT_PORCENTAJE             1043
#define IDC_EDIT_MONTO2                 1043
#define IDC_CHECK_PROMOCION_ACTIVA      1044
#define IDC_COMBO1                      1048
#define IDC_EDIT_SUBT                   1049
#define IDC_EDIT_DESCU                  1050
#define IDC_EDIT_TOTAL                  1051
#define IDC_BUT_GUARDAR                 1052
#define IDC_LIST_CONSUMOS               1053
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1054
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
